version: "2.4"

volumes:
  redical-search-storage:

services:
  unit-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    entrypoint:
      - sh
      - -c
      - "poetry install && script/test-continuous"
    environment:
      - PYTHONASYNCIODEBUG=1
    restart: on-failure
    tty: true
    volumes:
      - ./:/code:rw

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - redis
    entrypoint:
      - sh
      - -c
      - "poetry install && script/test-integration-continuous"
    environment:
      - PYTHONASYNCIODEBUG=1
      - REDICALSEARCH_REDIS_URI=redis://redis:6379
    restart: on-failure
    tty: true
    volumes:
      - ./:/code:rw

  redis:
    image: redislabs/redisearch:latest
    ports:
      - ${REDICALSEARCH_REDIS_PORT:-6479}:6379
    volumes:
      - redical-search-storage:/data
