version: "2.4"

volumes:
  aioredisearch-storage:

services:
  aioredisearch-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    entrypoint:
      - sh
      - -c
      - "poetry install && script/test-continuous"
    environment:
      - PYTHONASYNCIODEBUG=1
    restart: on-failure
    tty: true
    volumes:
      - ./:/code:rw

  aioredisearch-integration-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - redis
    entrypoint:
      - sh
      - -c
      - "poetry install && script/test-integration-continuous"
    environment:
      - PYTHONASYNCIODEBUG=1
    restart: on-failure
    tty: true
    volumes:
      - ./:/code:rw

  redis:
    image: redislabs/redisearch:latest
    ports:
      - ${AIOREDISEARCH_PORT:-6479}:6379
    volumes:
      - aioredisearch-storage:/data
