version: "2.4"

volumes:
  redical-search-storage:

services:
  unit-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: redical-search-unit-tests
    entrypoint:
      - sh
      - -c
      - script/test-continuous
    environment:
      # mypy can't seem to find the `py.typed` file now that `redical` is explicitly being
      # listed as a dependency in "develop" mode. This is a work around for now.
      - MYPYPATH=$MYPYPATH:/code/lib/redical
      - PYTHONASYNCIODEBUG=1
    restart: on-failure
    tty: true
    volumes:
      - ./:/code:rw

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: redical-search-integration-tests
    depends_on:
      - redis
    entrypoint:
      - sh
      - -c
      - script/test-integration-continuous
    environment:
      # mypy can't seem to find the `py.typed` file now that `redical` is explicitly being
      # listed as a dependency in "develop" mode. This is a work around for now.
      - MYPYPATH=$MYPYPATH:/code/lib/redical
      - PYTHONASYNCIODEBUG=1
      - REDICALSEARCH_REDIS_URI=redis://redis:6379
    restart: on-failure
    tty: true
    volumes:
      - ./:/code:rw

  redis:
    image: redislabs/redisearch:latest
    ports:
      - ${REDICALSEARCH_REDIS_PORT:-6479}:6379
    volumes:
      - redical-search-storage:/data
