#!/bin/sh

# script/lint: Run the linter on the project's files (including tests).
#              Optionally pass in a path to an individual file to
#              lint *only* that file.

bold="\033[0;1m"
blue="\033[0;34m"
green="\033[0;32m"
normal="\033[0;39m"
red="\033[0;31m"

set -e

cd "$(dirname "$0")/.."

echo "${blue}===> Linting files...${normal}"

echo -n ${bold}${red}
if [ -n "$1" ]; then
  flake8 "$1"
  result=$?
else
  flake8 redicalsearch/ && flake8 tests/
  result=$?
fi
echo -n ${normal}

if [ "$result" -eq "0" ]; then
  echo ${bold}${green}Success ${normal}
fi

echo "${blue}<=== Done.${normal}"

if [ "${result}" -ne "0" ]; then
  exit 1
fi
